#!/usr/bin/env bash
# Checks for cmd line arguments
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assigns parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4


# Disables strict host key check
scp -o "StrictHostKeyCheck=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checks if file transfer was successful
if [ $? -eq 0 ]
then
  echo "FILE TRANSFERED SUCCESSFULLY"
else
  echo "FILE TRANSFER FAILED"
fi
