#!/usr/bin/env bash
# Configures Ubuntu machine to Perform a 301-redirection

# Updates packages before installations
sudo apt-get update
sudo apt-get install -y nginx

# Creates index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performs 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/CTHartze permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarts Nginx service
sudo service nginx restart
