#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a 2 second interval in between each iteration.
#   Displays "I am invincible!!!" during each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
